### ISSUE TITLE
New URL shortener

### ISSUE THREAD

**Issue by fbordas** [Nechigawara/nechi-fgo-checklist#3]
In order to remove the dependency on Heroku, the link to shorten the list URL could be changed to use **_is.gd_** as a shortener provider, which has an open API that can be used easily.

`<a href='javascript:window.open("http://is.gd/create.php?url="+encodeURIComponent(location.href),"_blank")'>Shorten</a>`

Since the list URL changes dynamically as the contents change, this would ensure that the produced shortened URL would point to the currently active URL (and thus the currently active list).

**Comment by Nechigawara** [comment]
Oh, that's nice. Will Try it on Dev Branch Now.
