### ISSUE TITLE
Permission to continue the project/fork?

### ISSUE THREAD

**Issue by fbordas** [Nechigawara/nechi-fgo-checklist#7]
@Nechigawara I just read the notice that you've decided to stop playing the game. So I'd like to request official permission to continue updating as more Servants get implemented. I'll probably use a secondary Github account to separate my hobbyist works like this from my main account (fbordas). Also, even though the included MIT license enables modification and redistribution, I'd like to do it with the original author's blessing.

**Comment by Nechigawara** [comment]
Yep, you can do it.

**Comment by TohnoCoding** [comment]
I have started to work on the new site, Nechi. (I'm fbordas, this my hobbyist account. My fbordas account is usually reserved for work stuff.) The new fork is located at https://tohnocoding.github.io/fgochecklist/

Thank you so much for allowing me to continue with your amazing project.

**Comment by TohnoCoding** [comment]
Hi Nechi. If and when you can, I'd like you to take a look at the current state of the webapp I inherited from you. I hope you'll be proud of what I've done with it. :)
